config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :vespas, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:show, :new, :create]
    resources :reviews, only: [:index, :show, :new, :create]
  end
  resources :bookings, only: [:index] do
    member do
      patch :confirm
    end
  end
  get 'pages/offers'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :vespa

  def confirm!
    update!(confirmation: true)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :vespa
  belongs_to :user
  validates :coment, presence: true
  validates :rating, presence: true, inclusion: { in: 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :vespas, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_many :owner_bookings, through: :vespas, source: :bookings
end

app/models/vespa.rb
class Vespa < ApplicationRecord
    include PgSearch::Model
  pg_search_scope :search_by_address_or_cylinder,
    against: [ :address, :cylinder ],
    using: {
      tsearch: { prefix: true } # <-- now `las vega la` will return something!
    }
  belongs_to :user
  has_many  :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy

  has_many_attached :photos

  validates :name, presence: true, uniqueness: true
  validates :model, presence: true
  validates :cylinder, presence: true, inclusion: { in: %w(50cc 125cc 250cc 300cc Electrique)}
  validates :description, presence: true
  validates :price, presence: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

def self.search(search)
  if search
    Vespa.where('lower(address) LIKE ?', search[:address].downcase)
  else
    Vespa.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @vespa = Vespa.find(params[:vespa_id])
    @booking = Booking.new
  end

  def create
    @vespa = Vespa.find(params[:vespa_id])
    @booking = Booking.new(booking_strong_param)
    @booking.vespa = @vespa
    @booking.user = current_user
    if @booking.save
      redirect_to bookings_path, notice: "Votre reservation a été effectuée"
    end
  end

  def show
  end

  def index
    @bookings       = current_user.bookings.order(date: :desc)
    @owner_bookings = current_user.owner_bookings.order(date: :desc)
  end

  def confirm
    @booking = Booking.find(params[:id])
    @booking.confirm!
    redirect_to bookings_path
  end

  private

  def booking_strong_param
    params.require(:booking).permit(:date)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
skip_before_action :authenticate_user!, only: :home

  def home
  end

  def offers
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @vespa = Vespa.find(params[:vespa_id])
    @review = Review.new(review_strong_param)
  end

  def index
    @review = Review.all
  end

  def show
  end

  def create
    @vespa = Vespa.find(params[:vespa_id])
    @review = Review.new(review_strong_param)
    @review.vespa = @vespa
    @review.user = current_user
    if @review.save
      redirect_to @vespa, notice: "Votre commentaire a été déposé"
    end
  end

  private

  def review_strong_param
    params.require(:review).permit(:coment, :rating)
  end

end

app/controllers/vespas_controller.rb
class VespasController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show]

  def index
    if params[:query].present?
      @vespas = Vespa.near(params[:query])
    else
      @vespas = Vespa.geocoded
    end
      @markers = @vespas.map do |vespa|
      {
        lat: vespa.latitude,
        lng: vespa.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { vespa: vespa })
      }
    end
  end

  def new
    @vespa = Vespa.new
  end

  def create
    @vespa = Vespa.new(vespas_strong_params)
    @vespa.user = current_user
    if @vespa.save
      redirect_to vespa_path(@vespa)
    else
      render 'new'
    end
  end

  def show
    @vespa = Vespa.find(params[:id])
    @booking = Booking.new
    @review = Review.new
    @booked_by_current_user = booked_by_current_user?
  end

  def edit
    @vespa = Vespa.find(params[:id])
  end

  def update
    @vespa = Vespa.find(params[:id])
    @vespa.update!(vespas_strong_params)

    redirect_to vespa_path(@vespa)
  end

  def destroy
    @vespa = Vespa.find(params[:id])
    @vespa.destroy!

    redirect_to pages_offers_path
  end

  private

  def booked_by_current_user?
    users = @vespa.bookings.map do |booking|
      booking.user
    end
    users.include?(current_user)
  end

   def vespas_strong_params
    params.require(:vespa).permit(:name, :model, :cylinder, :description, :price, :address, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<%= simple_form_for [vespa, booking] do |f| %>
  <%= f.input :date %>
  <hr>
  <%= f.button :submit, class: "btn btn-outline-danger w-100", value: "Réserver" %>
<% end %>

app/views/bookings/create.html.erb
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/index.html.erb
<% if @bookings.empty? %>
    <% else %>
<h1 class='title-page'>Mes réservations</h1>
  <div class="container" style="padding: 15px 0 30px 0">

    <table class="table table-bordered">
    <thead style="background-color: #c8d8d5; color: white">
      <tr>
        <th scope="col">Loueur</th>
        <th scope="col">Votre Vespa</th>
        <th scope="col">Réservée pour le</th>
        <th scope="col">Tarif</th>
        <th scope="col">Statut de la réservation</th>
      </tr>
    </thead>

    <% @bookings.each do |booking| %>
      <tbody>
        <tr>
          <td><small class="text-muted"></small> <%= booking.vespa.user.first_name %> <%= booking.vespa.user.last_name %> </td>
          <td><small class="text-muted"></small>  <%= booking.vespa.model %> </td>
          <td><small class="text-muted"></small>  <%= booking.date %> </td>
          <td><small class="text-muted"></small> <%= booking.vespa.price %> euros</td>
          <td><small class="text-muted"></small>
            <% if booking.confirmation == false %>
              <strong>En attente de confirmation</strong>
            <% else %>
              <strong>Confirmé</strong>
            <% end %>
          </td>
    <% end %>
  </table>
  </div>
<% end %>

<% if @owner_bookings.empty? %>
    <% else %>
<h1 class='title-page'>Mes réservations à traiter</h1>
  <div class="container" style="padding: 15px 0 30px 0">
    <table class="table table-bordered">
    <thead style="background-color: #c8d8d5; color: white">
      <tr>
        <th scope="col">Client</th>
        <th scope="col">Vespa réservée</th>
        <th scope="col">Réservée pour le</th>
        <th scope="col">Tarif</th>
        <th scope="col">Statut de la réservation</th>
      </tr>
    </thead>

    <% @owner_bookings.each do |booking| %>
      <tbody>
        <tr>
          <td><small class="text-muted"></small> <%= booking.user.first_name %> <%= booking.user.last_name %> </td>
          <td><small class="text-muted"></small>  <%= booking.vespa.model %> </td>
          <td><small class="text-muted"></small>  <%= booking.date %> </td>
          <td><small class="text-muted"></small> <%= booking.vespa.price %> euros</td>
          <td><small class="text-muted"></small>
            <% if booking.confirmation == false %>
             <%= link_to confirm_booking_path(booking), method: :patch do  %>
               <button class="btn btn-outline-danger w-100">Confirmer</button>

             <% end %>
            <% else %>
            <strong><%= "Confirmé" %></strong>
            <% end %>
          </td>
    <% end %>
  </table>
  </div>
<% end %>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PRIMAVERA</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="bodyhomepage">
  <div>
    <div class="container-top">
    <div class="container">
    <div class="java">
        <h1>Louez une vespa à <span id="banner-typed-text"></span></h1>
        <h2 ></h2>
        <div id="banner-typed-text"></div>
    </div>
  <br>
        <h1>
          <span id="banner-typed-text"></span>
        </h1>

    <div class="formgroup">
        <%= form_tag vespas_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "form-control input",
        placeholder: "Choisis ton endroit.."
        %>
        <% end %>
      </div>
    </div>
  </div>


  <div class="container">
      <hr>
        <div class="cards-home row">
          <div class="col-8 col-md-8 col-lg-3">
            <%= link_to "/vespas?query=Saint-Étienne" do %>
              <div class="card-home" id="etienne">
                <h2>St-Etienne</h2>
              </div>
            <% end %>
          </div>
          <%= link_to "/vespas?query=Lyon" do %>
            <div class="col-8 col-md-8 col-lg-3">
              <div class="card-home" id="lyon">
                <h2>Lyon</h2>
              </div>
          <% end %>
            </div>
          <%= link_to "/vespas?query=Rome" do %>
            <div class="col-8 col-md-8 col-lg-3">
              <div class="card-home"  id="rome">
                <h2>Rome</h2>
              </div>
          <% end %>
            </div>
          </div>
      <hr>
  </div>

  <div class="footer">
        <div class="footercoopyright">
          <img height="30" src="https://image.flaticon.com/icons/png/512/68/68328.png" alt="icone">
          © 2020 Primavera, Inc. All rights reserved
        </div>
        <div class="footerlinks">
          <a href="#">
            <i class="fab fa-instagram">
            </i>
          </a>
          <a href="#">
            <i class ="fab fa-facebook">
            </i>
          </a>
          <a href="#">
            <i class ="fab fa-twitter">
            </i>
          </a>
        </div>
  </div>
</div>

app/views/pages/offers.html.erb
<h1 class='title-page'>Mes Vespas</h1>
<div class="cards-offre">
  <% current_user.vespas.each do |vespa| %>
    <div class="card-offre">
      <div>
      <%= cl_image_tag vespa.photos[0], height: 200, width: 300, crop: :fill if vespa.photos.attached? %>
      </div>
      <div class="card-offre-infos">
        <div class="card-offre-text">
          <h2><%= vespa.model %></h2>
          <p><%= vespa.cylinder %></p>
          <p><%= vespa.price %> € / jour</p>
        </div>
        <div class="card-offre-button">
          <div class="btn btn-light">
            <%= link_to "Mettre à jour", edit_vespa_path(vespa) %>
          </div>
           <div class="btn btn-danger">
            <%= link_to "Supprimer", vespa_path(vespa), method: :delete %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/reviews/_new.html.erb
<%= simple_form_for [vespa, review] do |f| %>
  <%= f.input :coment %>
  <%= f.input :rating %>
  <hr>
  <%= f.button :submit, class: "btn btn-outline-danger w-100", value: "Commenter" %>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="home">
    <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "https://www.stickpng.com/assets/images/580b585b2edbce24c47b2d18.png" %>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="navbar-nav mr-auto">
        <% if user_signed_in? %>

        <div class="navbar-center">
          <p class="nav-item">
            <%= link_to "Publier une offre", new_vespa_path, class: "nav-link" %>
          </li>
          <p class="nav-item">
            <%= link_to "Mes vespas", pages_offers_path, class: "nav-link" %>
          </li>
          <p class="nav-item">
            <%= link_to "Mes réservations", bookings_path, class: "nav-link" %>
          </li>
        </div>
      </div>
    </div>
      <div class="right">

        <div class="right-margin">
          <%= current_user.first_name %>
        </div>

        <div class="avatar">

            <div class="nav-item dropdown">

              <%= image_tag "https://www.lettrepub.fr/storage/stickers/Sticker%20visage%20homme%20BAR08.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                
              </div>
          </div>
        </div>
      </div>
        <% else %>
          <p class="nav-item-logout">
            <%= link_to "Se connecter", new_user_session_path, class: "nav-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/vespas/_info_window.html.erb
<h2> Réserver chez <%= vespa.user.first_name %></h2>
<p><%= vespa.address %></p>

app/views/vespas/destroy.html.erb
<h1>Vespas#destroy</h1>
<p>Find me in app/views/vespas/destroy.html.erb</p>

app/views/vespas/edit.html.erb
<h1 class='title-page'>Modifier cette offre</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">


      <%= simple_form_for @vespa do |f| %>
        <%= f.input :name, label: 'Titre de votre annonce' %>
        <%= f.input :model, label: 'Modele' %>
        <%= f.input :cylinder, label: 'Cylindrée : 50|125|250|300|Electrique', collection: ["50cc","125cc","250cc","300cc","Electrique"] %>
        <%= f.input :description %>
        <%= f.input :photos, as: :file, input_html: { multiple: true }  %>
        <%= f.input :price, label: 'Tarif à la journée'%>
        <%= f.input :address, label: 'Veuillez choisir une adresse' %>
        <%= f.button :submit, "Valider", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/vespas/index.html.erb
<h1 class='title-page'>Résultat de la recherche</h1>
<div class="results-container">
  <div class="cards-result">
    <div style="list-style-type: none">
      <% @vespas.each do |vespa| %>
        <div class="card-result">
          <div>
          <%= cl_image_tag vespa.photo.key, height: 200, width: 300, crop: :fill if vespa.photo.attached? %>
          </div>
          <div class="card-result-text">
            <div class="card-result-infos">
              <h2><%= vespa.name %></h2>
              <p><%= vespa.cylinder %> - <%= vespa.model %></p>
              <hr>
              <h2>Chez <%= vespa.user.first_name %> <%= vespa.user.last_name %> !</h2>
            </div>
            <div class="card-result-pricing">
              <h2><%= vespa.price %> € / jour</h2>
              <div class="btn btn-info">
                <%= link_to "Plus d'info", vespa_path(vespa) %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div
    id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/vespas/new.html.erb
<h1 class='title-page'>Publier une nouvelle offre</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= simple_form_for @vespa do |f| %>
        <%= f.input :name, label: 'Titre de votre annonce' %>
        <%= f.input :model, label: 'Modèle' %>
        <%= f.input :cylinder, label: 'Cylindrée : 50|125|250|300|Electrique', collection: ["50cc","125cc","250cc","300cc","Electrique"] %>
        <%= f.input :description %>
        <%= f.input :photo, as: :file %>
        <%= f.input :price, label: 'Tarif à la journée'%>
        <%= f.input :address %>
        <%= f.button :submit, "Valider", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/vespas/show.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1507416051062-8a3d4f400399?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2850&q=80)">
  <%= @vespa.name %>
</div>



  <div class="container">

      <!--  CONTENT -->

    <div class="row">
      <div class="col-md-8">
         <div class="card card-outline-secondary my-4">
          <div class="card-header">
            <h2><strong>Modele - <%= @vespa.model %> - <%= @vespa.cylinder%></strong></h2>
          </div>
          <div class="card-body">
            <p> Description de mon offre :
              <hr>
              <%= @vespa.description %>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi dolor, dolore, quae quisquam porro eaque odio cum aut. Suscipit velit fuga, modi expedita aut sed quae obcaecati eos voluptates sint!</p>
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card card-outline-secondary my-4" id="booking">
          <div class="card-header">
            <h4 style="text-align: center"><strong>Votre rêve pour</strong></h4>
            <hr>
            <h5 style="text-align: center"><%= @vespa.price %> euros / jour</h5>
          </div>
          <div class="card-body">
            <%= render "bookings/new", vespa: @vespa, booking: @booking %>
          </div>
        </div>
      </div>
    </div>

  <!--  PHOTOS -->

    <div class="row">
      <div class="col-md-12">
        <div class="card card-outline-secondary my-4" id="photos">
          <div class="card-header">
            <h2><strong>Photos</strong></h2>
          </div>

          <div class="cards">

            <% @vespa.photos.each do |photo| %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path(photo.key) %>)">
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  <!--  BOOKING PART -->
    <div class="row">
      <div class="col-md-12">
         <div class="card card-outline-secondary my-4" id="review">
          <div class="card-header">
            <h2><strong>Mes commentaires</strong></h2>
          </div>
          <div class="card-body">

              <% @vespa.reviews.each do |review| %>

              <li class="list-group-item d-flex justify-content-between align-items-center">
                <span class="badge badge-primary badge-pill">
                  <% counter = 0 %>
                  <% 5.times do %>
                    <i class="fa <%= review.rating > counter ? 'fa-star' : 'fa-star-o' %>"></i>
                    <% counter += 1 %>
                  <% end %>
                </span>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                  <%= review.coment %>
                   <p><small class="text-muted">Commentaire posté par</small> <strong> <%= review.user.first_name %> </strong> <small class="text-muted">le 28/02/2020</small></p>
                </li>
              </li>
              <br>
            <% end %>

            <hr>
               <% if @booked_by_current_user %>
                  <!-- Button trigger modal -->
                <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#exampleModal">
                  Deposer un commentaire
                </button>

                <!-- Modal button commentaire-->
                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Formulaire de commentaire</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <%= render "reviews/new", vespa: @vespa, review: @review %>
                      </div>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>

          </div>
        </div>
      </div>
     </div>
  </div>